version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - bot-network

  # Сервис базы данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: tg_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testbotdb
    ports:
      - "8081:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network: