version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/testbotdb
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/testbotdb
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
    networks:
      - bot-network

  postgres:
    image: postgres:15-alpine
    container_name: tg_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testbotdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network: