spring:
  application:
    name: tg-test-bot
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/testbotdb
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgres:5432/testbotdb
    user: postgres
    password: postgres

logging:
  level:
    root: INFO
  charset:
    console: UTF-8

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:snptgtestbot}
    token: ${TELEGRAM_BOT_TOKEN:7547525460:AAFkPC03wRNogQmErT-FoHM4gqiXbNgCrkM}
    path: ${TELEGRAM_BOT_PATH:path}
